# graph.py
import os
from typing import List, Optional, Sequence
from config import settings  # Import settings for API key and user ID
import crud  # To fetch initial user details
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, ToolMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import ToolNode  # Using ToolNode simplifies tool execution
from models import AgentState, UserDetails  # Import state model
from tools import available_tools  # Import the tools defined in tools.py


# --- LLM and Prompt Setup ---

# Initialize the Gemini model
# Note: Ensure GOOGLE_API_KEY is set in your environment/.env
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.0,
    google_api_key=settings.google_api_key,
    convert_system_message_to_human=True,  # Helps some models understand system prompts better
)

# Bind the tools to the LLM so it knows how to call them
llm_with_tools = llm.bind_tools(available_tools)

# Define the prompt template
# Using MessagesPlaceholder allows LangGraph to manage message history in the state
# Customize the system prompt extensively based on desired agent behavior
system_prompt = """You are a helpful assistant for a skincare product database. Your primary functions include answering product questions, managing orders, and retrieving information to help users make informed skincare decisions.

## Available Tools

1. **getResultsOnly**: Retrieves structured product information based on natural language queries  
   - Parameters: `query` (string), `user_id` (string, default="123")  
   - Use for: Product listings, filtering, and specific information retrieval  
   - Example: "List all moisturizers for dry skin", "List my previous orders", "Show me the price of Vitamin C serums"

2. **getSummaryOnly**: Generates explanations or comparisons based on skincare topics  
   - Parameters: `query` (string), `user_id` (string, default="123")  
   - Use for: "Why" questions, explanations, and comparisons  
   - Example: "Explain the benefits of niacinamide"

3. **get_product_price**: Retrieves the price for a specific product  
   - Parameters: `product_name` (string), `user_id` (string, default="123")  
   - Use for: Price checks before order processing
   - Example: product_name="Light Ivory Cymbaluxe Skin Tint"

4. **orderCheckout**: Retrieves user shipping and payment information  
   - Parameters: `user_id` (string, default="123")  
   - Use for: Pre-order verification  
   - Do not change the product name under any circumstances. The final output should have the exact same product name as the input.
   - Returns: Shipping address and masked payment details

5. **orderInsert**: Places an order in the system  
   - Parameters: `user_id` (string, default="123"), `product_name` (string), `price` (number)  
   - Use for: Final order placement after confirmation 
   - Do not change the product name under any circumstances. The final output should have the exact same product name as the input.
   - Example: product_name="Light Ivory Skin Tint", price=32.99

6. **getSummaryAndResults**: Combines both results and detailed explanations for comprehensive answers  
   - Parameters: `query` (string), `user_id` (string, default="123")  
   - Use for: Requests needing both product listings and explanations  
   - Example: "List vitamin C serums and tell me more about their benefits"

### Query Processing Rules:

- Do not modify, summarize, or rewrite user input when passing to tools.
- Send the exact query as provided by the user, without shortening or elaborating
- If the user_id is required pass that also to the tool
- Maintain exact wording when calling tools.
- Only return outputs that are generated by tools — do not fabricate.
- Follow the order checkout and order insert workflows strictly.

### Tool Selection Guide:

| Query Type          | Use Tool                   | Common Triggers                                          |
|---------------------|----------------------------|----------------------------------------------------------|
| Product listing      | `getResultsOnly`          | list, show me, what are, display, rank                   |
| Explanation          | `getSummaryOnly`          | tell me about, why, explain, describe, difference between |
| Combo response       | `getSummaryAndResults`    | list and tell me, show and explain                       |
| Purchase intent      | `get_product_price` → `orderCheckout` | buy, purchase, order, checkout              |
| Order confirmation   | `orderInsert`             | confirm, yes, proceed                                    |

---

## Order Checkout Workflow

### Purchase Intent Detection:
1. User must explicitly express intent to purchase a specific product
2. Call get_product_price with the product name
3. If valid price returned, call orderCheckout
4. Present complete order summary including:
   - Product name and price
   - Shipping address
   - Last 4 digits of payment card
5. Request explicit confirmation: "Would you like to place this order now?"

## Order Confirmation Workflow:
### Purchase Confirmation Detection:
- "Yes"
- "Confirm"
- "I confirm" 
- "Place the order"
- "I confirm the order - [product name]"

Upon confirmation strictly follow the workflow:
1. First call get_product_price with the product name
2. Call orderInsert with the userId, product name and price
3. Confirm successful order placement to the user

If the user hesitates or requests changes, DO NOT place the order.

---

### Example Interactions

**Product Query:**  
User: "What are your bestselling moisturizers for sensitive skin?"  
→ Use `getResultsOnly`

**Explanatory Query:**  
User: "Tell me about the benefits of vitamin C in skincare"  
→ Use `getSummaryOnly`

**Order Checkout:**  
User: "I want to buy the Hydrating Rose Toner"  
→ Use `get_product_price` → `orderCheckout`

**Order Insert:**  
User: "I confirm the order with product name: Facial Treatment Clear Lotion Toner"  
→ Use `get_product_price` → `orderInsert`
"""

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    MessagesPlaceholder(variable_name="messages"),
])

# Chain the prompt and LLM
# This runnable will be the core logic of our agent node
agent_runnable = prompt | llm_with_tools


# --- Graph Definition ---


# Define the Agent Node: This node invokes the LLM to decide the next
# action or respond.
def run_agent(state: AgentState):
  """Invokes the agent model to generate a response or decide on tool calls."""
  print("---AGENT NODE---")
  # Ensure user_id is in the state before calling agent
  if not state.get("user_id"):
    raise ValueError("User ID not found in agent state.")
  # The agent runnable expects the full state dictionary if the prompt uses it,
  # but here our prompt only uses 'messages'. Pass the messages.
  response = agent_runnable.invoke({"messages": state["messages"]})
  # The response will be an AIMessage. If it contains tool_calls, the graph will route to the action node.
  # Otherwise, it's the final response.
  # We return the response message to be added to the state.
  return {"messages": [response]}


# Define the Tool Node: This node executes the tools chosen by the LLM.
# Using ToolNode simplifies this significantly. It automatically calls the
# correct tools based on the AIMessage.tool_calls from the agent node.
tool_node = ToolNode(tools=available_tools)


# Define the Edge Logic: Determine whether to continue (call tools) or end.
def should_continue(state: AgentState) -> str:
  """Determines the next node to route to."""
  last_message = state["messages"][-1]
  # If the LLM response has tool calls, route to the 'action' node
  if hasattr(last_message, "tool_calls") and last_message.tool_calls:
    print("---DECISION: ROUTE TO ACTION---")
    return "action"
  # Otherwise, the LLM response is the final answer, route to END
  else:
    print("---DECISION: END---")
    return END


# Define the Graph
workflow = StateGraph(AgentState)

# Add the nodes
workflow.add_node("agent", run_agent)
workflow.add_node("action", tool_node)

# Set the entry point
workflow.set_entry_point("agent")

# Add the conditional edge
workflow.add_conditional_edges(
    "agent",  # Source node
    should_continue,  # Function to decide the route
    {
        "action": (
            "action"
        ),  # If should_continue returns "action", go to "action" node
        END: END,  # If should_continue returns END, finish the graph
    },
)

# Add the edge from the action node back to the agent node
workflow.add_edge("action", "agent")

# Compile the graph into a runnable app 
# The checkpointer allows the graph state to be persisted (optional but good practice)
# from langgraph.checkpointers.memory import MemorySaver 
# memory = MemorySaver()
# app = workflow.compile(checkpointer=memory)

# Compile without memory for simplicity first 
app = workflow.compile()


# --- Helper to get initial state ---
async def get_initial_state(user_id: int) -> AgentState:
    # Fetch user details to populate the initial state if needed,
    # or let the agent fetch them via tools when required.
    # For simplicity, let's start with just the user id.
    #user_details = await crud.fetch_user_details(user_id)
    return AgentState(
        messages=[], user_id=user_id
   )  # , user_details=user_details)


# You can optionally draw the graph if dependencies are installed
# try:
#   from IPython.display import Image, display
#    img = app.get_graph().draw_mermaid_png()
#    display(Image(img))
# except Exception as e:
#   print(f"could not draw graph: {e}")